name: linkfive_purchases_example
description: Demonstrates how to use the linkfive_purchases plugin.
version: 0.0.1+1

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  linkfive_purchases: ^3.0.0
  #path: ../packages/linkfive_purchases
  linkfive_purchases_provider: ^3.0.0
    #path: ../packages/linkfive_purchases_provider
  in_app_purchases_paywall_ui: ^1.0.1
  in_app_purchases_intl: ^1.0.1
  #path: ../../in_app_purchases_paywall/packages/in_app_purchases_paywall_ui
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dependency_overrides:
  in_app_purchases_intl: ^1.0.1
  in_app_purchases_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/apikey.json
