// Mocks generated by Mockito 5.2.0 from annotations
// in linkfive_purchases/test/store/linkfive_purchases_main_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:in_app_purchase/in_app_purchase.dart' as _i3;
import 'package:in_app_purchase_platform_interface/in_app_purchase_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeProductDetailsResponse_0 extends _i1.Fake
    implements _i2.ProductDetailsResponse {}

/// A class which mocks [InAppPurchase].
///
/// See the documentation for Mockito's code generation for more information.
class MockInAppPurchase extends _i1.Mock implements _i3.InAppPurchase {
  MockInAppPurchase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.PurchaseDetails>> get purchaseStream =>
      (super.noSuchMethod(Invocation.getter(#purchaseStream),
              returnValue: Stream<List<_i2.PurchaseDetails>>.empty())
          as _i4.Stream<List<_i2.PurchaseDetails>>);
  @override
  T getPlatformAddition<T extends _i2.InAppPurchasePlatformAddition?>() =>
      throw UnsupportedError(
          '\'getPlatformAddition\' cannot be used without a mockito fallback generator.');
  @override
  _i4.Future<bool> isAvailable() =>
      (super.noSuchMethod(Invocation.method(#isAvailable, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.ProductDetailsResponse> queryProductDetails(
          Set<String>? identifiers) =>
      (super.noSuchMethod(
              Invocation.method(#queryProductDetails, [identifiers]),
              returnValue: Future<_i2.ProductDetailsResponse>.value(
                  _FakeProductDetailsResponse_0()))
          as _i4.Future<_i2.ProductDetailsResponse>);
  @override
  _i4.Future<bool> buyNonConsumable({_i2.PurchaseParam? purchaseParam}) =>
      (super.noSuchMethod(
          Invocation.method(
              #buyNonConsumable, [], {#purchaseParam: purchaseParam}),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<bool> buyConsumable(
          {_i2.PurchaseParam? purchaseParam, bool? autoConsume = true}) =>
      (super.noSuchMethod(
          Invocation.method(#buyConsumable, [],
              {#purchaseParam: purchaseParam, #autoConsume: autoConsume}),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<void> completePurchase(_i2.PurchaseDetails? purchase) =>
      (super.noSuchMethod(Invocation.method(#completePurchase, [purchase]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> restorePurchases({String? applicationUserName}) =>
      (super.noSuchMethod(
          Invocation.method(#restorePurchases, [],
              {#applicationUserName: applicationUserName}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}
